image:
  file: .gitpod.Dockerfile

additionalRepositories:
  - url: https://github.com/json-schema-org/JSON-Schema-Test-Suite
    checkoutLocation: json-schema-test-suite

  # TODO: referencing-suite and others, once Bowtie supports them

tasks:
  - name: Install Bowtie
    init: python3 -m pip install -r requirements.txt -e .

  - name: Pull Bowtie Images
    init: for each in $(ls implementations); do docker pull ghcr.io/bowtie-json-schema/$each; done
