repos:
  - repo: https://github.com/dustinsand/pre-commit-jvm
    rev: v0.7.0
    hooks:
      - name: PMD (java implementations)
        id: pmd
        args:
          [
            "--rulesets",
            "implementations/java-implementations-pmd-ruleset.xml",
            "implementations",
          ]
