repos:
  - repo: https://github.com/gherynos/pre-commit-java
    rev: v0.2.9
    hooks:
      - name: PMD (java implementations)
        id: pmd
        args:
          [
            "-R",
            "implementations/.java-implementations-pmd-ruleset.xml",
            "-d",
            "implementations",
          ]
  - repo: https://github.com/dustinsand/pre-commit-jvm
    rev: v0.8.0
    hooks:
      - name: detekt
        id: detekt
        args:
          [
            "--build-upon-default-config",
            "--input",
            "implementations/kotlin-kmp-json-schema-validator",
          ]
