name: Deploy frontend UI with test reports to GH pages

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"
      - ".github/workflows/build-frontend.yml"

jobs:
  build-frontend:
    uses: ./.github/workflows/build-frontend.yml
  collect:
    runs-on: ubuntu-latest
    needs: build-frontend
    steps:
      - name: Create _site directory
        run: mkdir _site
      - name: Download frontend build
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: _site

      - name: Download latest test report
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: report.yml
          branch: main
          name: report
          path: _site
          # empty string for any conclusion
          workflow_conclusion: ''

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: collect
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
