name: Lint code

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - uses: pmd/pmd-github-action@v1
        id: pmd
        with:
          sourcePath: 'implementations/'
          rulesets: 'pmd-ruleset.xml'
      - name: Fail build if there are lint errors
        if: steps.pmd.outputs.violations != 0
        run: echo "::error pmd analysis failed with {steps.pmd.outputs.violations} lint errors"
