name: Test Suite Report

on:
  release:
    types: [published]
  workflow_dispatch:
  schedule:
    # Daily at 2:15
    - cron: "15 2 * * *"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - draft2020-12
          - draft2019-09
          - draft7
          - draft6
          - draft4
          - draft3

    steps:
      - run: touch ${{ matrix.version }}.jsonl

      - uses: actions/upload-artifact@v3
        with:
          name: report
          path: |
            ${{ matrix.version }}.jsonl

  deploy-frontend:
    needs: test
    uses: ./.github/workflows/deploy-frontend.yml
    with:
      report_artifact_in_scope: true
